include:
  - component: gitlab.themeinerlp.dev/onelitefeather/ci-components/pnpm-build@0.0.5
  - component: gitlab.themeinerlp.dev/onelitefeather/ci-components/docker-build@0.0.5
    inputs:
      step_deploy-container_needs:
        - build