onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@intlify/core-base@>=10.0.0 <10.0.8': '>=10.0.8'
  '@intlify/core@>=10.0.0 <10.0.8': '>=10.0.8'
  '@nuxt/devtools@<2.6.4': '>=2.6.4'
  '@nuxtjs/mdc@<0.17.2': '>=0.17.2'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  ipx@>=2.0.0-0 <2.1.1: '>=2.1.1'
  koa@>=2.0.0 <2.16.2: '>=2.16.2'
  nuxt@>=3.6.0 <3.19.0: '>=3.19.0'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
  vue-i18n@>=10.0.0 <10.0.8: '>=10.0.8'
