<script setup lang="ts">
/**
 * Winter's decoration: an ice crystal in both top corners and, from md up
 * and only when motion is welcome, up to six slowly falling snowflakes.
 * Colours are role tokens with opacity, same pattern as the other seasons.
 */

/**
 * A proper six-fold crystal, mirrored for the right-hand corner: six arms on
 * an exact 60° grid from the centre, each with two pairs of side branches
 * partway along it (shorter towards the tip). Replaces an earlier version
 * whose arms sat on an uneven grid and carried V-shaped tips — it read as
 * arrows, not a snowflake. Generated by a small script (60°-spaced points,
 * branches at 45%/72% of the radius); see the commit for the script.
 */
const CRYSTAL = 'M50 50L50 8 M40.5 25.6L50 31.1L59.5 25.6 M43.9 16.3L50 19.8L56.1 16.3 '
  + 'M50 50L86.4 29 M66.4 29.6L66.4 40.6L75.9 46.1 M76.2 27.9L76.2 34.9L82.3 38.4 '
  + 'M50 50L86.4 71 M75.9 54L66.4 59.5L66.4 70.5 M82.3 61.6L76.2 65.1L76.2 72.1 '
  + 'M50 50L50 92 M59.5 74.4L50 68.9L40.5 74.4 M56.1 83.7L50 80.2L43.9 83.7 '
  + 'M50 50L13.6 71 M33.6 70.5L33.6 59.5L24.1 54 M23.8 72.1L23.8 65.1L17.7 61.6 '
  + 'M50 50L13.6 29 M24.1 46.1L33.6 40.6L33.6 29.6 M17.7 38.4L23.8 34.9L23.8 27.9'

/** A small six-fold snowflake, drifting slowly downward — the same shape as
 * the corner crystal, scaled down to one branch pair per arm. */
const SNOWFLAKE = 'M8 8L8 1 M5.7 2.8L8 4.1L10.3 2.8 '
  + 'M8 8L14.1 4.5 M11.3 3.5L11.3 6.1L13.6 7.4 '
  + 'M8 8L14.1 11.5 M13.6 8.6L11.3 9.9L11.3 12.5 '
  + 'M8 8L8 15 M10.3 13.2L8 11.9L5.7 13.2 '
  + 'M8 8L1.9 11.5 M4.7 12.5L4.7 9.9L2.4 8.6 '
  + 'M8 8L1.9 4.5 M2.4 7.4L4.7 6.1L4.7 3.5'

const SNOWFLAKE_CLASS = 'absolute hidden animate-season-fall text-tertiary/40 motion-safe:md:block'

/** Where each flake starts and how its fall is offset. Six at most (spec). */
const SNOWFLAKES = [
  { position: 'top-[8%] left-[15%] h-3 w-3', delay: '[animation-delay:-2s]' },
  { position: 'top-[4%] left-[42%] h-4 w-4', delay: '[animation-delay:-9s]' },
  { position: 'top-[10%] left-[68%] h-3 w-3', delay: '[animation-delay:-15s]' },
  { position: 'top-[2%] left-[85%] h-4 w-4', delay: '[animation-delay:-6s]' },
  { position: 'top-[14%] left-[28%] h-2 w-2', delay: '[animation-delay:-19s]' },
  { position: 'top-[6%] left-[55%] h-3 w-3', delay: '[animation-delay:-12s]' },
]
</script>

<template>
  <!-- -left-6/-right-6 (rather than the halloween web's -1) keep most of the
       crystal off the 32px content gutter (lg:px-8) that opens up right
       where the layout is tightest, ~1024-1280px; lg:h-24/w-24 caps the size
       there too instead of growing straight from the sm: step. -->
  <svg
    v-for="side in ['-left-6', '-right-6 -scale-x-100']"
    :key="side"
    :class="['absolute top-16 h-20 w-20 text-primary/25 sm:h-28 sm:w-28 lg:h-24 lg:w-24', side]"
    data-decor="crystal"
    viewBox="0 0 100 100"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    <path :d="CRYSTAL" />
  </svg>

  <!-- Snowflakes stay off small screens and off entirely under reduced
       motion, opt-in the same way the halloween bats are (motion-safe:md:
       block, not motion-reduce:hidden — see the comment on SeasonDecorHalloween's
       bats about Tailwind v4's variant order). -->
  <svg
    v-for="flake in SNOWFLAKES"
    :key="flake.position"
    :class="[SNOWFLAKE_CLASS, flake.position, flake.delay]"
    data-decor="snowflake"
    viewBox="0 0 16 16"
    fill="none"
    stroke="currentColor"
    stroke-width="1.5"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    <path :d="SNOWFLAKE" />
  </svg>
</template>
