<script setup lang="ts">
/**
 * New year's decoration: a small sparkle cluster in both top corners and,
 * from md up and only when motion is welcome, up to five gently twinkling
 * light points plus up to four firework buckets at the page edges (spec
 * new-year-season, "Neujahrs-Deko mit sanftem Feuerwerk"). No explosions,
 * full-surface flashes or red — a bucket only scales and fades open, over
 * at least a second, then glimmers back out.
 */

/** A four-pointed star, mirrored for the right-hand corner, plus two smaller
 * satellite stars so the corner reads as a sparkle cluster rather than one
 * cutout. All three share the star-point construction (outer/inner radius
 * on a 45° grid), just at different centres and sizes. */
const STAR = 'M50 8l9 33 33 9-33 9-9 33-9-33-33-9 33-9z'
const STAR_SATELLITE_1 = 'M78 11L80.5 19.5L89 22L80.5 24.5L78 33L75.5 24.5L67 22L75.5 19.5Z'
const STAR_SATELLITE_2 = 'M18 74L19.8 80.2L26 82L19.8 83.8L18 90L16.2 83.8L10 82L16.2 80.2Z'

const LIGHT_CLASS = 'absolute hidden rounded-full animate-season-twinkle bg-secondary/70 motion-safe:md:block'

/** Where each light sits and how its twinkle is offset. Five at most (spec). */
const LIGHTS = [
  { position: 'top-[10%] left-[20%] h-2 w-2', delay: '[animation-delay:0s]' },
  { position: 'top-[5%] left-[45%] h-2.5 w-2.5', delay: '[animation-delay:-1.5s]' },
  { position: 'top-[12%] left-[62%] h-2 w-2', delay: '[animation-delay:-3s]' },
  { position: 'top-[3%] left-[80%] h-2.5 w-2.5', delay: '[animation-delay:-2.25s]' },
  { position: 'top-[16%] left-[35%] h-1.5 w-1.5', delay: '[animation-delay:-0.75s]' },
]

/**
 * A real firework burst: sixteen rays on a 22.5° grid, starting away from
 * the centre (inner radius ~15, 30% of the 50-radius viewBox) rather than
 * meeting at a hub, alternating long and short so it reads as an irregular
 * spray. A small dot sits just beyond each long ray's tip. No line crosses
 * the centre — the earlier ten-spoke version, all lines through a single
 * hub, read as a ball-and-stick model rather than a firework. Generated by
 * a small script; see the commit for it.
 */
const BURST_RAYS = 'M66 50L96 50 M62.9 55.4L81.4 63 M61.3 61.3L82.5 82.5 M55.4 62.9L63 81.4 M50 66L50 96 '
  + 'M44.6 62.9L37 81.4 M38.7 61.3L17.5 82.5 M37.1 55.4L18.6 63 M34 50L4 50 M37.1 44.6L18.6 37 '
  + 'M38.7 38.7L17.5 17.5 M44.6 37.1L37 18.6 M50 34L50 4 M55.4 37.1L63 18.6 M61.3 38.7L82.5 17.5 '
  + 'M62.9 44.6L81.4 37'
const BURST_DOTS: Array<[number, number]> = [
  [99.5, 50],
  [85, 85],
  [50, 99.5],
  [15, 85],
  [0.5, 50],
  [15, 15],
  [50, 0.5],
  [85, 15],
]

const BURST_CLASS = 'absolute hidden animate-season-burst motion-safe:md:block'

/**
 * Where each bucket sits, its colour role and how its opening is staggered.
 * Four at most (spec). `left-[max(0.5rem,2%)]` keeps a bucket's centre
 * inside the page gutter even on narrow viewports, rather than a bare `2%`
 * drifting arbitrarily close to the edge; at 1280px the gutter runs to
 * ~90px, so a bucket may still lap ~20px onto the content, which the low
 * opacity and short peak (see animate-season-burst) keep unobtrusive. The
 * 1.75s stagger over the 7s cycle keeps buckets from ever opening together
 * (design D5). Two buckets in the bright, unharmonised brand-orange, one
 * each in tertiary and secondary for variety.
 */
const BURSTS = [
  {
    edge: 'left-[max(0.5rem,2%)]',
    top: 'top-[25%]',
    colour: 'text-brand-orange/70',
    delay: '[animation-delay:0s]',
  },
  {
    edge: 'right-[max(0.5rem,2%)]',
    top: 'top-[42%]',
    colour: 'text-tertiary/70',
    delay: '[animation-delay:-1.75s]',
  },
  {
    edge: 'left-[max(0.5rem,2%)]',
    top: 'top-[58%]',
    colour: 'text-brand-orange/70',
    delay: '[animation-delay:-3.5s]',
  },
  {
    edge: 'right-[max(0.5rem,2%)]',
    top: 'top-[75%]',
    colour: 'text-secondary/70',
    delay: '[animation-delay:-5.25s]',
  },
]
</script>

<template>
  <svg
    v-for="side in ['-left-1', '-right-1 -scale-x-100']"
    :key="side"
    :class="['absolute top-16 h-16 w-16 text-brand-orange/50 sm:h-20 sm:w-20', side]"
    data-decor="star"
    viewBox="0 0 100 100"
    fill="currentColor"
  >
    <path :d="STAR" />
    <path :d="STAR_SATELLITE_1" />
    <path :d="STAR_SATELLITE_2" />
  </svg>

  <!-- Light points stay off small screens and off entirely under reduced
       motion, opt-in the same way the halloween bats are (motion-safe:md:
       block, not motion-reduce:hidden — see the comment on SeasonDecorHalloween's
       bats about Tailwind v4's variant order). A background colour twinkles
       via opacity/scale only: no explosion, no full-surface flash. -->
  <span
    v-for="light in LIGHTS"
    :key="light.position"
    :class="[LIGHT_CLASS, light.position, light.delay]"
    data-decor="light"
  />

  <!-- Firework buckets sit at the edges, outside the reading column, and
       only ever scale + fade (animate-season-burst) — never a brightness or
       colour flash, and staggered so at most one opens at a time. -->
  <svg
    v-for="burst in BURSTS"
    :key="`${burst.edge}-${burst.top}`"
    :class="[
      BURST_CLASS, burst.colour, burst.edge, burst.top, burst.delay,
      'h-24 w-24 lg:h-28 lg:w-28 xl:h-36 xl:w-36',
    ]"
    data-decor="burst"
    viewBox="0 0 100 100"
    fill="currentColor"
    stroke="currentColor"
    stroke-width="2.4"
    stroke-linecap="round"
  >
    <path :d="BURST_RAYS" fill="none" />
    <circle
      v-for="[cx, cy] in BURST_DOTS"
      :key="`${cx}-${cy}`"
      :cx="cx"
      :cy="cy"
      r="1.5"
      stroke="none"
    />
  </svg>
</template>
