<script setup lang="ts">
/**
 * New year's decoration: a star in both top corners and, from md up and only
 * when motion is welcome, up to five gently twinkling light points plus up
 * to four firework buckets at the page edges (spec new-year-season, "Neujahrs-
 * Deko mit sanftem Feuerwerk"). No explosions, full-surface flashes or red —
 * a bucket only scales and fades open, over at least a second, then glimmers
 * back out.
 */

/** A four-pointed star, mirrored for the right-hand corner. */
const STAR = 'M50 8l9 33 33 9-33 9-9 33-9-33-33-9 33-9z'

const LIGHT_CLASS = 'absolute hidden rounded-full animate-season-twinkle bg-secondary/70 motion-safe:md:block'

/** Where each light sits and how its twinkle is offset. Five at most (spec). */
const LIGHTS = [
  { position: 'top-[10%] left-[20%] h-2 w-2', delay: '[animation-delay:0s]' },
  { position: 'top-[5%] left-[45%] h-2.5 w-2.5', delay: '[animation-delay:-1.5s]' },
  { position: 'top-[12%] left-[62%] h-2 w-2', delay: '[animation-delay:-3s]' },
  { position: 'top-[3%] left-[80%] h-2.5 w-2.5', delay: '[animation-delay:-2.25s]' },
  { position: 'top-[16%] left-[35%] h-1.5 w-1.5', delay: '[animation-delay:-0.75s]' },
]

/**
 * A ten-spoke spark ring: alternating long and short lines from the centre,
 * each ending in a small dot, on an exact 36° grid — the same generated-path
 * approach as the winter snowflake, so it reads as a burst rather than a
 * blot. Generated by a small script; see the commit for it.
 */
const BURST_LINES = 'M50 50L90 50 M50 50L72.7 66.5 M50 50L62.4 88 M50 50L41.3 76.6 M50 50L17.6 73.5 '
  + 'M50 50L22 50 M50 50L17.6 26.5 M50 50L41.3 23.4 M50 50L62.4 12 M50 50L72.7 33.5'
const BURST_DOTS: Array<[number, number]> = [
  [90, 50],
[72.7, 66.5],
[62.4, 88],
[41.3, 76.6],
[17.6, 73.5],
  [22, 50],
[17.6, 26.5],
[41.3, 23.4],
[62.4, 12],
[72.7, 33.5],
]

const BURST_CLASS = 'absolute hidden animate-season-burst motion-safe:md:block'

/**
 * Where each bucket sits, its colour role and how its opening is staggered.
 * Four at most (spec), at the page edges outside the reading column, further
 * out still from `lg` where the content column has more room to breathe.
 * The 1.75s stagger over the 7s cycle keeps buckets from ever opening
 * together (design D5).
 */
const BURSTS = [
  { edge: 'left-[2%] lg:left-[1%]', top: 'top-[20%]', colour: 'text-secondary/70', delay: '[animation-delay:0s]' },
  { edge: 'right-[2%] lg:right-[1%]', top: 'top-[38%]', colour: 'text-tertiary/70', delay: '[animation-delay:-1.75s]' },
  { edge: 'left-[2%] lg:left-[1%]', top: 'top-[55%]', colour: 'text-brand-orange/70', delay: '[animation-delay:-3.5s]' },
  { edge: 'right-[2%] lg:right-[1%]', top: 'top-[70%]', colour: 'text-secondary/70', delay: '[animation-delay:-5.25s]' },
]
</script>

<template>
  <svg
    v-for="side in ['-left-1', '-right-1 -scale-x-100']"
    :key="side"
    :class="['absolute top-16 h-28 w-28 text-secondary/25 sm:h-36 sm:w-36', side]"
    data-decor="star"
    viewBox="0 0 100 100"
    fill="currentColor"
  >
    <path :d="STAR" />
  </svg>

  <!-- Light points stay off small screens and off entirely under reduced
       motion, opt-in the same way the halloween bats are (motion-safe:md:
       block, not motion-reduce:hidden — see the comment on SeasonDecorHalloween's
       bats about Tailwind v4's variant order). A background colour twinkles
       via opacity/scale only: no explosion, no full-surface flash. -->
  <span
    v-for="light in LIGHTS"
    :key="light.position"
    :class="[LIGHT_CLASS, light.position, light.delay]"
    data-decor="light"
  />

  <!-- Firework buckets sit at the edges, outside the reading column, and
       only ever scale + fade (animate-season-burst) — never a brightness or
       colour flash, and staggered so at most one opens at a time. -->
  <svg
    v-for="burst in BURSTS"
    :key="`${burst.edge}-${burst.top}`"
    :class="[
      BURST_CLASS, burst.colour, burst.edge, burst.top, burst.delay, 'h-28 w-28 lg:h-36 lg:w-36',
    ]"
    data-decor="burst"
    viewBox="0 0 100 100"
    fill="currentColor"
    stroke="currentColor"
    stroke-width="2.5"
    stroke-linecap="round"
  >
    <path :d="BURST_LINES" fill="none" />
    <circle
      v-for="[cx, cy] in BURST_DOTS"
      :key="`${cx}-${cy}`"
      :cx="cx"
      :cy="cy"
      r="2.6"
      stroke="none"
    />
  </svg>
</template>
