import { queryCollection } from '#imports'
import type { Locale } from './collections'
import type { ContentRepository } from './repository'
import type { BlogArticle, BlogAuthorProfile } from '~/types/blog'
import type { FaqEntry, TeamFaqEntry } from '~/types/faq'
import type { TeamDocument } from '~/types/team'
import type {
  ServerConceptDocument,
  ServerConnectDocument,
  HomeCarouselDocument
} from '~/types/home'
import type { SponsorsDocument } from '~/types/sponsoring'

// The `authors` collection is declared in `content.config.ts`, so its types
// are generated by @nuxt/content — no module augmentation needed here.

// Collection-key naming is a @nuxt/content implementation detail and must
// stay confined to this file.
const blogKey = (locale: Locale) => `blog_${locale}` as 'blog_de' | 'blog_en'
const faqKey = (locale: Locale) => `faq_${locale}` as 'faq_de' | 'faq_en'
const teamFaqKey = (locale: Locale) => `team_faq_${locale}` as 'team_faq_de' | 'team_faq_en'
const teamKey = (locale: Locale) => `team_${locale}` as 'team_de' | 'team_en'
const sponsorsKey = (locale: Locale) => `sponsors_${locale}` as 'sponsors_de' | 'sponsors_en'
const serverConceptKey = (locale: Locale) => `server_concept_${locale}` as 'server_concept_de' | 'server_concept_en'
const serverConnectKey = (locale: Locale) => `server_connect_${locale}` as 'server_connect_de' | 'server_connect_en'
const homeCarouselKey = (locale: Locale) => `home_carousel_${locale}` as 'home_carousel_de' | 'home_carousel_en'

/**
 * The @nuxt/content-backed {@link ContentRepository} implementation. Every
 * `queryCollection` call in the app is funnelled through here. All methods
 * must run inside a Nuxt context (e.g. an `useAsyncData` fetcher), which is
 * how `queryCollection` resolves the active Nuxt app.
 */
export function createNuxtContentAdapter(): ContentRepository {
  return {
    listBlogArticles(locale) {
      return queryCollection(blogKey(locale))
        .order('pubDate', 'DESC')
        .all() as Promise<BlogArticle[]>
    },

    getBlogArticleBySlug(locale, slug) {
      return queryCollection(blogKey(locale))
        .where('slug', '=', slug)
        .first() as Promise<BlogArticle | null>
    },

    getBlogArticleByTranslationKey(locale, translationKey) {
      return queryCollection(blogKey(locale))
        .where('translationKey', '=', translationKey)
        .first() as Promise<BlogArticle | null>
    },

    getAuthorBySlug(slug) {
      return queryCollection('authors')
        .where('slug', '=', slug)
        .first() as Promise<BlogAuthorProfile | null>
    },

    listFaqEntries(locale) {
      return queryCollection(faqKey(locale))
        .order('order', 'ASC')
        .all() as Promise<FaqEntry[]>
    },

    async getTeamDocument(locale) {
      const docs = await queryCollection(teamKey(locale)).all()
      return (docs[0] ?? null) as TeamDocument | null
    },

    listTeamFaqEntries(locale) {
      return queryCollection(teamFaqKey(locale))
        .order('order', 'ASC')
        .all() as Promise<TeamFaqEntry[]>
    },

    async getServerConcept(locale) {
      const docs = await queryCollection(serverConceptKey(locale)).all()
      return (docs[0] ?? null) as ServerConceptDocument | null
    },

    async getServerConnect(locale) {
      const docs = await queryCollection(serverConnectKey(locale)).all()
      return (docs[0] ?? null) as ServerConnectDocument | null
    },

    async getHomeCarousel(locale) {
      const docs = await queryCollection(homeCarouselKey(locale)).all()
      return (docs[0] ?? null) as HomeCarouselDocument | null
    },

    getSponsorsDocument(locale) {
      return queryCollection(sponsorsKey(locale))
        .first() as Promise<SponsorsDocument | null>
    }
  }
}
