import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { collectSourceFiles, relativeToRepo } from '../helpers/sources'

/**
 * `title` and `aria-label` are read to the user — the first as a tooltip, the
 * second as the accessible name a screen reader announces in place of the
 * element. Written as a plain attribute they bypass `t()` entirely, so they
 * stay in whichever language the author happened to be thinking in while the
 * visible text beside them switches locale.
 *
 * The accessible-name case is the worse of the two, because nothing on screen
 * reveals it: a German-language page can announce an English control name to
 * a screen-reader user and look perfectly translated to everyone else.
 *
 * Scope: the static attribute form only. The bound form (`:title="'…'"`) has
 * its own set of offenders in the carousel and is handled separately — this
 * check does not claim the tree is free of those.
 */

const SOURCE_DIRS = ['components',
  'pages',
  'layouts']

/**
 * `title="…"` / `aria-label="…"` with at least one letter, but not the bound
 * form (`:title=`) and not a longer attribute ending in the same word
 * (`data-title=`).
 */
const STATIC_TEXT_ATTRIBUTE = /(?<![\w:.@-])(title|aria-label)="([^"]*[A-Za-z][^"]*)"/g

/**
 * `pages/privacy.vue` carries the attribution link generated by
 * datenschutz-generator.de verbatim. Its wording is part of the legal text and
 * is not ours to rephrase or key, so the whole page stays out until that text
 * is reviewed as a whole.
 */
const EXEMPT = new Set(['pages/privacy.vue'])

function offenders(): string[] {
  const found: string[] = []
  for (const file of collectSourceFiles(SOURCE_DIRS, ['.vue'])) {
    const relative = relativeToRepo(file)
    if (EXEMPT.has(relative)) continue
    const text = readFileSync(file, 'utf8')
    text.split('\n').forEach((line, index) => {
      STATIC_TEXT_ATTRIBUTE.lastIndex = 0
      for (const [, attribute,
value] of line.matchAll(STATIC_TEXT_ATTRIBUTE)) {
        found.push(`${relative}:${index + 1} — ${attribute}="${value}"`)
      }
    })
  }
  return found
}

describe('user-visible attributes', () => {
  it('tells the static form from the bound one', () => {
    // Without this the check could pass by matching nothing at all.
    const hits = (line: string) => {
      STATIC_TEXT_ATTRIBUTE.lastIndex = 0
      return [...line.matchAll(STATIC_TEXT_ATTRIBUTE)].map(([, , value]) => value)
    }
    expect(hits('<a aria-disabled="true" title="Coming soon">')).toEqual(['Coming soon'])
    expect(hits('<iframe title="BlueMap" loading="lazy" />')).toEqual(['BlueMap'])
    // Already routed through t() — the bound form is not this check's business.
    expect(hits('<a :title="t(\'footer.coming_soon\')">')).toEqual([])
    // A different attribute that merely ends in the same word.
    expect(hits('<div data-title="Coming soon">')).toEqual([])
    // Nothing to translate.
    expect(hits('<img placeholder="empty" title="" />')).toEqual([])
  })

  it('no title or aria-label is written as untranslated text', () => {
    expect(offenders()).toEqual([])
  })
})
