import { queryCollection } from '#imports'
import type { Locale } from './collections'
import type {
  ContentRepository,
  SponsorsDocument,
  TeamDocument,
  BlogArticle,
  BlogAuthorProfile,
  ServerConceptDocument,
  ServerConnectDocument,
  HomeCarouselDocument,
  CommunityPoiDocument,
  CommunityPoiSummary,
  EventDocument,
  EventSummary
} from './repository'
import type { FaqEntry, TeamFaqEntry } from '../../types-faq'

// The `authors` collection is declared in `content.config.ts`, so its types
// are generated by @nuxt/content — no module augmentation needed here.

// Collection-key naming is a @nuxt/content implementation detail and must
// stay confined to this file.
const blogKey = (locale: Locale) => `blog_${locale}` as 'blog_de' | 'blog_en'
const faqKey = (locale: Locale) => `faq_${locale}` as 'faq_de' | 'faq_en'
const teamFaqKey = (locale: Locale) => `team_faq_${locale}` as 'team_faq_de' | 'team_faq_en'
const teamKey = (locale: Locale) => `team_${locale}` as 'team_de' | 'team_en'
const sponsorsKey = (locale: Locale) => `sponsors_${locale}` as 'sponsors_de' | 'sponsors_en'
const serverConceptKey = (locale: Locale) => `server_concept_${locale}` as 'server_concept_de' | 'server_concept_en'
const serverConnectKey = (locale: Locale) => `server_connect_${locale}` as 'server_connect_de' | 'server_connect_en'
const homeCarouselKey = (locale: Locale) => `home_carousel_${locale}` as 'home_carousel_de' | 'home_carousel_en'
const communityPoiKey = (locale: Locale) => `community_poi_${locale}` as 'community_poi_de' | 'community_poi_en'
const eventsKey = (locale: Locale) => `events_${locale}` as 'events_de' | 'events_en'

type CommunityPoiQuery = ReturnType<typeof queryCollection<'community_poi_de' | 'community_poi_en'>>

function communityPoiSummaries(query: CommunityPoiQuery) {
  return query.select(
    'slug',
    'title',
    'summary',
    'status',
    'progress',
    'category',
    'featured',
    'featuredCaption',
    'thumbnail',
    'thumbnailAlt',
    'location',
    'acceptsContributions',
    'builders',
    'startedAt',
    'updatedAt',
    'gallery',
    'schematics'
  )
}

const toCommunityPoiSummary = (row: Record<string, unknown>): CommunityPoiSummary => {
  const { gallery, schematics, ...rest } = row
  return {
    ...rest,
    galleryCount: Array.isArray(gallery) ? gallery.length : 0,
    schematicCount: Array.isArray(schematics) ? schematics.length : 0
  } as CommunityPoiSummary
}

/**
 * The @nuxt/content-backed {@link ContentRepository} implementation. Every
 * `queryCollection` call in the app is funnelled through here. All methods
 * must run inside a Nuxt context (e.g. an `useAsyncData` fetcher), which is
 * how `queryCollection` resolves the active Nuxt app.
 */
type Query = typeof queryCollection

export function createNuxtContentAdapter(query: Query = queryCollection): ContentRepository {
  return {
    // Projected, not `SELECT *`. This feeds one screen — the overview's
    // headline card and teaser grid — and without a projection every row
    // carries `body`, the article's full minimark AST, all the way into the
    // SSR payload.
    //
    // `excerpt` rather than `body` is the load-bearing choice. ArticleCard
    // renders `<ContentRenderer :value="blogArticle" :excerpt="true">`, which
    // needs a parsed tree — but @nuxt/content stores the excerpt as its own
    // column, so the card gets what it draws and nothing else.
    //
    // `releaseDate` is in the list but on no card: the release gate in
    // useBlogContent reads it. Trimming this to what the templates show would
    // publish unreleased articles. The contract is asserted in
    // tests/content/blog-list-projection.spec.ts.
    listBlogArticles(locale) {
      return query(blogKey(locale))
        .select(
          // ContentRenderer emits it as data-content-id; without it the
          // rendered excerpt is identical but loses that attribute.
          'id',
          'slug',
          'title',
          'alternativeTitle',
          'description',
          'excerpt',
          'headerImage',
          'headerImageAlt',
          'pubDate',
          'releaseDate',
          'tags'
        )
        .all() as Promise<BlogArticle[]>
    },

    getBlogArticleBySlug(locale, slug) {
      return query(blogKey(locale))
        .where('slug', '=', slug)
        .first() as Promise<BlogArticle | null>
    },

    getBlogArticleByTranslationKey(locale, translationKey) {
      return query(blogKey(locale))
        .where('translationKey', '=', translationKey)
        .first() as Promise<BlogArticle | null>
    },

    getAuthorBySlug(slug) {
      return query('authors')
        .where('slug', '=', slug)
        .first() as Promise<BlogAuthorProfile | null>
    },

    async listAuthorsBySlugs(slugs) {
      if (!slugs.length) return []
      return await query('authors')
        .select('slug', 'name', 'role', 'avatar', 'bio', 'links')
        .where('slug', 'IN', slugs)
        .all() as BlogAuthorProfile[]
    },

    listFaqEntries(locale) {
      return query(faqKey(locale))
        .order('order', 'ASC')
        .all() as Promise<FaqEntry[]>
    },

    getTeamDocument(locale) {
      return query(teamKey(locale))
        .first() as Promise<TeamDocument | null>
    },

    listTeamFaqEntries(locale) {
      return query(teamFaqKey(locale))
        .order('order', 'ASC')
        .all() as Promise<TeamFaqEntry[]>
    },

    getServerConcept(locale) {
      return query(serverConceptKey(locale))
        .first() as Promise<ServerConceptDocument | null>
    },

    getServerConnect(locale) {
      return query(serverConnectKey(locale))
        .first() as Promise<ServerConnectDocument | null>
    },

    getHomeCarousel(locale) {
      return query(homeCarouselKey(locale))
        .first() as Promise<HomeCarouselDocument | null>
    },

    getSponsorsDocument(locale) {
      return query(sponsorsKey(locale))
        .first() as Promise<SponsorsDocument | null>
    },

    // gallery and schematics are read only to be reduced to counts.
    listCommunityPois(locale) {
      return communityPoiSummaries(query(communityPoiKey(locale)))
        .all()
        .then((rows) => rows.map(toCommunityPoiSummary))
    },

    listFeaturedCommunityPois(locale) {
      return communityPoiSummaries(query(communityPoiKey(locale)))
        .where('featured', '=', true)
        .all()
        .then((rows) => rows.map(toCommunityPoiSummary))
    },

    getCommunityPoiBySlug(locale, slug) {
      return query(communityPoiKey(locale))
        .where('slug', '=', slug)
        .first() as Promise<CommunityPoiDocument | null>
    },

    getCommunityPoiByTranslationKey(locale, translationKey) {
      return query(communityPoiKey(locale))
        .where('translationKey', '=', translationKey)
        .first() as Promise<CommunityPoiDocument | null>
    },

    listEvents(locale) {
      return query(eventsKey(locale))
        .select(
          'slug',
          'title',
          'summary',
          'type',
          'thumbnail',
          'thumbnailAlt',
          'unlisted',
          'hosts',
          'event',
          'access',
          'promote',
          'results'
        )
        .all() as Promise<EventSummary[]>
    },

    getEventBySlug(locale, slug) {
      return query(eventsKey(locale))
        .where('slug', '=', slug)
        .first() as Promise<EventDocument | null>
    },

    getEventByTranslationKey(locale, translationKey) {
      return query(eventsKey(locale))
        .where('translationKey', '=', translationKey)
        .first() as Promise<EventDocument | null>
    }
  }
}
